language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t alexandrejeanjean/portfolio -f Dockerfile.dev .

script:
  - docker run -e CI=true alexandrejeanjean/portfolio yarn test

after_success:
  - docker build -t alexandrejeanjean/portfolio .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alexandrejeanjean/portfolio
